#!/bin/bash

# Install program and dependencies, if doesn't yet exist.
evnDependencies="git tig"
for evnDependency in $evnDependencies; do
	if [[ -z `command -v ${evnDependency}` ]]; then
		sudo apt-get install -y ${evnDependency}
	fi
done

# Link configurations
ln -s $HOME/.gitl/.gitconfig $HOME/.gitconfig
ln -s $HOME/.gitl/.tig.rc $HOME/.tig.rc

# Install libraries
cd /usr/local/share
sudo bash $HOME/.gitl/lib/git-flow/contrib/gitflow-installer.sh
cd -

# add this to .zshrc: "source ~/.git-flow-completion.zsh"