#!/bin/bash

# Install program and dependencies, if doesn't yet exist.
evnDependencies="tig"
for evnDependency in $evnDependencies; do
	if [[ -z `command -v ${evnDependency}` ]]; then
		sudo apt-get install -y ${evnDependency}
	fi
done

# Link configurations
ln -s $HOME/.git.d/.gitconfig $HOME/.gitconfig
ln -s $HOME/.git.d/.tig.rc $HOME/.tig.rc

# Install libraries
sudo apt-get install git-flow

# add this to .zshrc: "source $HOME/.git-flow-completion.zsh"