#!/usr/bin/ruby
# Encoding: utf-8

message_file = ARGV[0]
message = File.read(message_file)
$regex = /^(feat|fix|docs|style|refactor|test|chore|improve)\(([a-zA-Z]+)\)\:(.{0,50})$/

if !$regex.match(message)
puts "[POLICY] Your message is not formatted correctly.
Key points of a well formed commit message:
- Must have a summary line.
- Summary line must be 70 characters or less.
- Summary line syntax must be '<type>(<scope>): <subject>'.
- Should have a well thought out and meaningful description.
- No line in the description should be over 80 characters long.

Format breakdown:
- First line is summary.
- Second line is empty.
- Third line starts the in-depth description."
exit 1
end