#!/bin/bash

# Description  : Runs all executable <hook-name>.* hooks and exits after.
# Usage        :
# Dependencies :
# Example      :
# Notes        :
# Source       : [Chaining git hooks](http://stackoverflow.com/a/8734391)

data=$(cat)
exitcodes=()
hookname=`basename $0`

# Run each hook, passing through STDIN and storing the exit code.
# We don't want to bail at the first failure, as the user might
# then bypass the hooks without knowing about additional issues.

for hook in $GIT_DIR/hooks/$hookname.*; do
  test -x "$hook" || continue
  echo "$data" | "$hook"
  exitcodes+=($?)
done

# If any exit code isn't 0, bail.

for i in "${exitcodes[@]}"; do
  [ "$i" == 0 ] || exit $i
done