#!/usr/bin/env bash

# Description  : (Re)Initialize git hooks in all repos - downstream or upstream.
# Usage        :
# Dependencies :
# Example      :
# Notes        :
# Source       : http://stevenharman.net/git-clean-delete-already-merged-branches

set -x

TEST_BRANCH=".git/hooks/pre-receive.*"

REPO_DIR="/var/www/"
if [[ $USER == "git" ]]; then
  REPO_DIR="/home/git/repositories/"
fi

DEST_REPOS=`find $REPO_DIR -type f |     # List all files in the destination.
  grep "$TEST_BRANCH" |                  # List only repos in which the custom hooks are present.
  grep -Fv "vendor" |                    # Remove entries with vendors - we don't care about them.
  sed "s|$TEST_BRANCH||g" |              # Get the directory base name.
  uniq`                                  # List only Unique entries.

for REPO in $DEST_REPOS; do
  rm ${REPO}${TEST_BRANCH}
  [[ $USER == "git" ]] && git init --bare ${REPO}.git
  [[ $USER != "git" ]] && git init ${REPO}
done